### ISSUE TITLE
Ensure CircleCI executes jobs

### ISSUE THREAD

**Issue by joshua-rutherford** [DecipherNow/moby#17]
@Walterm21, I merged your last pull request before I took are very close look at the CircleCI output. While it is passing, it is not actually doing anything.  All it does is checkout the code: https://circleci.com/gh/DecipherNow/moby/43. 

I think you need to probably add workflows that call the jobs you defined.  I would assume something like the following:

```
version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: mvn verify
  deploy:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: PGP_RINGS="$(echo ${PGP_RINGS_ENCODED} | base64 --decode)" mvn deploy -P deploy -s settings.xml
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
        filters:
          branches:
            only: master
```
